### ISSUE TITLE
CMake consistency sweep for 4.3.1 release

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7263]
- ~~irods~~ - not needed
- irods_client_icommands
    - [x] irods/irods_client_icommands#405
    - [x] irods/irods_client_icommands#410
- [x] irods/irods_api_plugin_genquery2#62
- ~~irods_auth_plugin_kerberos~~ - inactive
- ~~irods_capability_indexing~~ - pending migration away from elasticlient
- ~~irods_capability_publishing~~ - pending migration away from elasticlient
- [x] irods/irods_capability_storage_tiering#218
- ~~irods_client_cli~~ - not ready
- ~~irods_client_globus_connector~~ - not ready
- [x] irods/irods_client_http_api#76
- ~~irods_client_rest_cpp~~ - not ready
- ~~irods_client_s3_cpp~~ - not ready
- [x] irods/irods_microservice_plugins_curl#54
- ~~irods_netcdf~~ - does not support 4.3 yet
- ~~irods_policy_composition_framework~~ - not ready
- ~~irods_project_template_cpp_api_plugin~~ - will be done post-release (#7265)
- ~~irods_project_template_cpp_client~~ - will be done post-release (#7265)
- ~~irods_project_template_cpp_microservice~~ - will be done post-release (#7265)
- ~~irods_project_template_cpp_resource_plugin~~ - will be done post-release (#7265)
- ~~irods_project_template_cpp_rule_engine_plugin~~ - will be done post-release (#7265)
- [x] irods/irods_resource_plugin_s3#2135
- [x] irods/irods_rule_engine_plugin_audit_amqp#120
- ~~irods_rule_engine_plugin_hard_links~~ - inactive
- [x] irods/irods_rule_engine_plugin_logical_quotas#96
- [x] irods/irods_rule_engine_plugin_metadata_guard#59
- ~~irods_rule_engine_plugin_python~~ - not needed
- ~~irods_rule_engine_plugins_policy~~ - not ready

**Comment by korydraughn** [comment]
Ignore the following repos. They are effectively inactive for the foreseeable future.
- hard links
- kerberos

Ignore anything related to policy composition too. Those projects need to be discussed/reviewed in full before we do anything with them. Same thing for irods_rule_engine_plugins_policy.

**Comment by SwooshyCueb** [comment]
Should we archive the kerberos and hard links repos then?

**Comment by trel** [comment]
not archive yet.   but it's on the table...

**Comment by trel** [comment]
Nice work.
