### ISSUE TITLE
Ensure RPM packages are collecting dependencies on all EL distros

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7281]
I suspect there are other repos that have the same problem that icommands did in #6564.
Let's go through the list of repos touched by #7263, plus irods_rule_engine_plugin_python and irods proper, and ensure that RPM packages are collecting dependencies properly.
- irods
    - [x] irods/irods#7284
    - [x] 4-3-stable
- [x] irods_api_plugin_genquery2
- [x] irods/irods_capability_storage_tiering#219
- [x] irods_client_http_api
- [x] irods/irods_microservice_plugins_curl#55
- [x] irods_resource_plugin_s3
- [x] irods_rule_engine_plugin_audit_amqp
- [x] irods/irods_rule_engine_plugin_logical_quotas#97
- [x] irods/irods_rule_engine_plugin_metadata_guard#60
- [x] irods_rule_engine_plugin_python
