### ISSUE TITLE
Add EL version to RPM package version strings

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7312]
- irods
    - [x] irods/irods#7332
    - [x] irods/irods#7339
- irods_client_icommands
    - [x] irods/irods_client_icommands#414
    - [x] irods/irods_client_icommands#416
- [x] irods/irods_api_plugin_genquery2#72
- ~~irods_auth_plugin_kerberos~~ - inactive
- ~~irods_capability_indexing~~ - pending migration away from elasticlient
- ~~irods_capability_publishing~~ - pending migration away from elasticlient
- [x] irods/irods_capability_storage_tiering#221
- ~~irods_client_cli~~ - not ready
- ~~irods_client_globus_connector~~ - not ready
- [x] irods/irods_client_http_api#102
- ~~irods_client_rest_cpp~~ - not ready
- ~~irods_client_s3_cpp~~ - not ready
- [x] irods/irods_microservice_plugins_curl#56
- ~~irods_netcdf~~ - does not support 4.3 yet
- ~~irods_policy_composition_framework~~ - not ready
- ~~irods_project_template_cpp_api_plugin~~ - will be done post-release (#7265)
- ~~irods_project_template_cpp_client~~ - will be done post-release (#7265)
- ~~irods_project_template_cpp_microservice~~ - will be done post-release (#7265)
- ~~irods_project_template_cpp_resource_plugin~~ - will be done post-release (#7265)
- ~~irods_project_template_cpp_rule_engine_plugin~~ - will be done post-release (#7265)
- [x] irods/irods_resource_plugin_s3#2136
- [x] irods/irods_rule_engine_plugin_audit_amqp#121
- ~~irods_rule_engine_plugin_hard_links~~ - inactive
- [x] irods/irods_rule_engine_plugin_logical_quotas#98
- [x] irods/irods_rule_engine_plugin_metadata_guard#61
- [x] irods/irods_rule_engine_plugin_python#164
- ~~irods_rule_engine_plugins_policy~~ - not ready
- ~~externals~~ - will be done with libstdc++ externals

----

I'm putting this in the 4.3.1 milestone, but I'm fine with bumping it to 4.3.2.

Similar to how we add the distro codename to deb package version strings, we need to add the el version to rpm package version strings.
We have different builds for different EL versions, and the standard practice is to have different package release strings for each. This has many benefits. To list a few:
- Differing filenames between EL versions means that the built packages can be placed in the same directory.
- Making the EL version part of the package release strings makes builds for newer EL versions have a higher package version, making upgrading to a new EL version smoother.
- Putting the EL version in the package version string makes it easy to verify that the package matches the EL version.
- It brings us closer to Normal and Boring

A few examples:

|                            |                                                                                                                   |
| :------------------------- | :---------------------------------------------------------------------------------------------------------------- |
| **Package**                | [`mariadb-5.5.68-1.el7.x86_64.rpm`](https://centos.pkgs.org/7/centos-x86_64/mariadb-5.5.68-1.el7.x86_64.rpm.html) |
| **EL version**             | 7                                                                                                                 |
| **EL flavor**              | CentOS                                                                                                            |
| **Package version string** | `5.5.68-1.el7`                                                                                                    |
| **Software version**       | `5.5.68`                                                                                                          |
| **Package release**        | `1.el7`                                                                                                           |

|                            |                                                                                                                                                               |
| :------------------------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| **Package**                | [`mariadb-connector-c-3.1.11-2.el8_3.x86_64.rpm`](https://almalinux.pkgs.org/8/almalinux-appstream-x86_64/mariadb-connector-c-3.1.11-2.el8_3.x86_64.rpm.html) |
| **EL version**             | 8 (8.3?)                                                                                                                                                      |
| **EL flavor**              | AlmaLinux                                                                                                                                                     |
| **Package version string** | `3.1.11-2.el8_3`                                                                                                                                              |
| **Software version**       | `3.1.11`                                                                                                                                                      |
| **Package release**        | `2.el8_3`                                                                                                                                                     |

|                            |                                                                                                                                                                                       |
| :------------------------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| **Package**                | [`mariadb-10.5.16-2.module_el8.6.0+3072+3c630e87.x86_64.rpm`](https://almalinux.pkgs.org/8/almalinux-appstream-x86_64/mariadb-10.5.16-2.module_el8.6.0+3072+3c630e87.x86_64.rpm.html) |
| **EL version**             | 8 (8.6.0)                                                                                                                                                                             |
| **EL flavor**              | AlmaLinux                                                                                                                                                                             |
| **Package version string** | `10.5.16-2.module_el8.6.0+3072+3c630e87`                                                                                                                                              |
| **Software version**       | `10.5.16`                                                                                                                                                                             |
| **Package release**        | `2.module_el8.6.0+3072+3c630e87`                                                                                                                                                      |

|                            |                                                                                                                                                                                       |
| :------------------------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| **Package**                | [`mariadb-10.5.16-2.module+el8.6.0+995+5ac2a483.x86_64.rpm`](https://rockylinux.pkgs.org/8/rockylinux-appstream-x86_64/mariadb-10.5.16-2.module+el8.6.0+995+5ac2a483.x86_64.rpm.html) |
| **EL version**             | 8 (8.6.0)                                                                                                                                                                             |
| **EL flavor**              | Rocky Linux                                                                                                                                                                           |
| **Package version string** | `10.5.16-2.module+el8.6.0+995+5ac2a483`                                                                                                                                               |
| **Software version**       | `10.5.16`                                                                                                                                                                             |
| **Package release**        | `2.module+el8.6.0+995+5ac2a483`                                                                                                                                                       |

|                            |                                                                                                                                                                                    |
| :------------------------- | :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Package**                | [`mariadb-10.5.9-1.module_el8.5.0+732+7afc82e7.x86_64.rpm`](https://centos.pkgs.org/8-stream/centos-appstream-x86_64/mariadb-10.5.9-1.module_el8.5.0+732+7afc82e7.x86_64.rpm.html) |
| **EL version**             | 8 (8.5.0)                                                                                                                                                                          |
| **EL flavor**              | CentOS Stream                                                                                                                                                                      |
| **Package version string** | `10.5.9-1.module_el8.5.0+732+7afc82e7`                                                                                                                                             |
| **Software version**       | `10.5.9`                                                                                                                                                                           |
| **Package release**        | `1.module_el8.5.0+732+7afc82e7`                                                                                                                                                    |

Loosely following these examples, I propose we set our package release strings using the following pattern:
`[package revision].el[el_version]`
If we need to be more specific about the EL version (we probably won't), then we should use dotted versions rather than underscored versions (`8.6` instead of `8_6`).

Let's not worry about RPM modules for the time being.

**Comment by korydraughn** [comment]
How important do you feel this is for 4.3.1?

**Comment by SwooshyCueb** [comment]
It's not super important for 4.3.1, more of an "if we've got time" kinda thing. I don't mind bumping to 4.3.2

**Comment by korydraughn** [comment]
Ok. If it's not absolutely needed, let's punt to 4.3.2.

**Comment by SwooshyCueb** [comment]
Given that all PRs are submitted save cherry-picks for irods and icommands, I'm gonna move this back to the 4.3.1 milestone. I would like to get it in 4.3.1 if we can.
