### ISSUE TITLE
release activities for 4.3.2

### ISSUE THREAD

**Issue by trel** [irods/irods#7686]
- [x] Server Version Bump (handled in https://github.com/irods/irods/issues/7531)
- [x] iCommands Version Bump (handled in https://github.com/irods/irods/issues/7531)
- [x] Plugin Version Bumps (handled in https://github.com/irods/irods/issues/7531)
- [x] Release Notes

**Comment by korydraughn** [comment]
Don't forget to add words to the release notes about this.
- https://github.com/irods/irods/issues/7570#issuecomment-2043304940
